spring:
  # MySQL Connection Setting
  datasource:
    url: jdbc:mysql://localhost:3306/javue?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: "0000"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  # Thymeleaf Setting
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5